language: bash
arch:
  - amd64
services:
  - docker
jobs:
  include:
    - stage: build branch
      script:
        - docker build -t chrisjohnson00/pushover_k8s_monitoring -f Dockerfile .
        - docker run chrisjohnson00/pushover_k8s_monitoring python -m flake8
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/pushover_k8s_monitoring chrisjohnson00/pushover_k8s_monitoring:$TRAVIS_BRANCH
        - docker push chrisjohnson00/pushover_k8s_monitoring:$TRAVIS_BRANCH
      if: tag is blank
    - stage: build tag
      script:
        - docker build -t chrisjohnson00/pushover_k8s_monitoring -f Dockerfile .
        - docker login --username=chrisjohnson00 --password=$DOCKER_HUB_PASSWORD
        - docker tag chrisjohnson00/pushover_k8s_monitoring chrisjohnson00/pushover_k8s_monitoring:$TRAVIS_TAG
        - docker push chrisjohnson00/pushover_k8s_monitoring:$TRAVIS_TAG
        - docker push chrisjohnson00/pushover_k8s_monitoring
      if: tag IS present
